# Generated by Django 3.2.6 on 2021-08-24 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='file',
            table='File',
        ),
    ]
