# Generated by Django 3.2.6 on 2021-08-30 08:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0005_alter_yolo_yolo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert_yolo',
            old_name='output',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='alert_yolo',
            old_name='remark',
            new_name='memo',
        ),
        migrations.RenameField(
            model_name='yolo',
            old_name='remark',
            new_name='memo',
        ),
        migrations.RemoveField(
            model_name='alert_yolo',
            name='alert_id',
        ),
        migrations.RemoveField(
            model_name='yolo',
            name='output',
        ),
        migrations.RemoveField(
            model_name='yolo',
            name='version',
        ),
        migrations.RemoveField(
            model_name='yolo',
            name='yolo_id',
        ),
        migrations.AddField(
            model_name='alert_yolo',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yolo',
            name='alert',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='yolo',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='alert_yolo',
            name='id',
            field=models.SlugField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='yolo',
            name='id',
            field=models.SlugField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
