# Generated by Django 3.2.6 on 2021-08-31 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0006_auto_20210830_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_yolo',
            name='memo',
            field=models.CharField(default='(none)', max_length=200),
        ),
        migrations.AlterField(
            model_name='yolo',
            name='memo',
            field=models.CharField(default='(none)', max_length=200),
        ),
    ]
