# Generated by Django 3.2.6 on 2021-08-31 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0007_auto_20210831_1436'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert_yolo',
            old_name='memo',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='yolo',
            old_name='memo',
            new_name='description',
        ),
    ]
