# Generated by Django 3.2.6 on 2021-09-07 08:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0008_auto_20210831_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='yolo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='yolo',
            name='alert',
            field=models.IntegerField(choices=[(0, '無危險行為'), (1, '存在危險行為'), (2, '位置')], default=0),
        ),
        migrations.AlterField(
            model_name='yolo',
            name='file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='yolo',
            name='timestamp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Alert_Yolo',
        ),
    ]
