# Generated by Django 3.2.6 on 2021-09-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0009_auto_20210907_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yolo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
