# Generated by Django 3.2.6 on 2021-09-07 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0010_alter_yolo_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.AlterField(
            model_name='yolo',
            name='alert',
            field=models.IntegerField(choices=[(0, '無危險行為'), (1, '存在危險行為'), (2, '未知')], default=0),
        ),
    ]
