# Generated by Django 3.2.6 on 2021-09-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0011_auto_20210907_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(verbose_name='date created'),
        ),
    ]
