# Generated by Django 3.2.6 on 2021-09-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0012_alter_test_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
    ]
