# Generated by Django 3.2.6 on 2021-09-07 08:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0014_auto_20210907_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yolo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
