# Generated by Django 3.2.6 on 2021-09-07 09:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0015_alter_yolo_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yolo_Files',
            fields=[
                ('id', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(blank=True, upload_to='Uploaded Files/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('yolo_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='yoloid', to='db_api.yolo')),
            ],
            options={
                'db_table': 'Yolo_Files',
            },
        ),
    ]
