# Generated by Django 3.2.6 on 2021-09-07 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0016_yolo_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yolo',
            name='file',
        ),
    ]
