# Generated by Django 3.2.6 on 2021-09-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0017_remove_yolo_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
