# Generated by Django 3.2.6 on 2021-09-22 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0018_alert_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert_data',
            name='id',
            field=models.IntegerField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
