# Generated by Django 3.2.6 on 2021-09-25 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0019_alter_alert_data_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='yolo_trail',
            fields=[
                ('id', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(default='(none)', max_length=200)),
                ('alert', models.IntegerField(choices=[(0, '無危險行為'), (1, '存在危險行為'), (2, '未知')], default=0)),
                ('image', models.ImageField(default='', upload_to='Uploaded Files/')),
            ],
            options={
                'db_table': 'yolo_trial',
            },
        ),
    ]
