# Generated by Django 3.2.6 on 2021-09-25 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0020_yolo_trail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='yolo_trail',
        ),
        migrations.RemoveField(
            model_name='yolo_files',
            name='file',
        ),
        migrations.RemoveField(
            model_name='yolo_files',
            name='yolo_id',
        ),
        migrations.AddField(
            model_name='yolo_files',
            name='image',
            field=models.ImageField(blank=True, upload_to='Uploaded Files/'),
        ),
        migrations.AlterField(
            model_name='alert_data',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='yolo_files',
            name='id',
            field=models.OneToOneField(max_length=50, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db_api.yolo'),
        ),
    ]
