# Generated by Django 3.2.6 on 2021-09-25 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0021_auto_20210925_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='yolo_files',
            name='yoloid',
            field=models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='db_api.yolo'),
        ),
        migrations.AlterField(
            model_name='yolo_files',
            name='id',
            field=models.SlugField(blank=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
