# Generated by Django 3.2.6 on 2021-09-25 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0022_auto_20210925_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yolo_files',
            old_name='yoloid',
            new_name='yolo_id',
        ),
    ]
