# Generated by Django 3.2.6 on 2021-09-26 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0027_delete_yolo_trial'),
    ]

    operations = [
        migrations.CreateModel(
            name='yolo_trial',
            fields=[
                ('id', models.SlugField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('alert', models.IntegerField(choices=[(0, '無危險行為'), (1, '存在危險行為'), (2, '未知')], default=0)),
                ('description', models.CharField(default='(none)', max_length=200)),
                ('image', models.ImageField(blank=True, default='', upload_to='Uploaded Files/')),
            ],
        ),
    ]
