# Generated by Django 3.2.6 on 2021-10-01 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0031_picture_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yolo_files',
            name='picture_box',
        ),
        migrations.AddField(
            model_name='yolo_files',
            name='picture_Identifier',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
