# Generated by Django 3.2.6 on 2021-10-01 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0032_auto_20211001_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yolo_files',
            name='picture_Identifier',
        ),
        migrations.AddField(
            model_name='picture_files',
            name='identifier',
            field=models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='db_api.yolo'),
        ),
    ]
