# Generated by Django 3.2.6 on 2021-10-01 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0033_auto_20211001_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture_files',
            name='id',
        ),
        migrations.AlterField(
            model_name='picture_files',
            name='identifier',
            field=models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='db_api.yolo'),
        ),
    ]
