# Generated by Django 3.2.6 on 2021-10-01 15:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0034_auto_20211001_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture_files',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='picture_files',
            name='identifier',
            field=models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='db_api.yolo'),
        ),
    ]
