# Generated by Django 3.2.6 on 2021-10-01 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0035_auto_20211001_2342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture_Files',
        ),
    ]
