# Generated by Django 3.2.6 on 2021-10-01 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0036_delete_picture_files'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='', upload_to='Uploaded Files/')),
                ('identifier', models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='db_api.yolo_files')),
            ],
        ),
    ]
