# Generated by Django 3.2.6 on 2021-10-01 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0037_picture_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture_files',
            name='identifier',
            field=models.ForeignKey(default='', max_length=50, on_delete=django.db.models.deletion.CASCADE, to='db_api.yolo'),
        ),
    ]
