# Generated by Django 3.2.6 on 2021-10-12 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0038_alter_picture_files_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture_files',
            name='identifier',
            field=models.CharField(max_length=50),
        ),
    ]
