# Generated by Django 3.2.6 on 2021-10-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0039_alter_picture_files_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture_files',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='picture_files',
            name='identifier',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
