# Generated by Django 3.2.6 on 2021-10-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0040_auto_20211018_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='yolo_files',
            name='send_alert',
            field=models.BooleanField(default=False),
        ),
    ]
