# Generated by Django 3.2.6 on 2021-10-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0041_yolo_files_send_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='yolo_files',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
