# Generated by Django 3.2.6 on 2021-11-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0042_yolo_files_memo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yolo',
            name='alert',
            field=models.IntegerField(choices=[(0, '無危險行為'), (1, '未正確配戴安全帽'), (2, '雙掛鉤未使用'), (3, '偵測到無安全網'), (4, '未知')], default=0),
        ),
    ]
