# Generated by Django 3.2.6 on 2021-11-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0045_yolo_image_shape'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yolo',
            name='image',
            field=models.CharField(blank=True, max_length=1000000, null=True),
        ),
    ]
