# Generated by Django 3.2.6 on 2021-11-10 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0046_alter_yolo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yolo',
            name='image',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
