# Generated by Django 3.2.6 on 2021-11-11 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0047_alter_yolo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yolo',
            name='image',
            field=models.CharField(blank=True, max_length=100000000, null=True),
        ),
    ]
