# Generated by Django 3.2.6 on 2021-09-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylinebot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='state',
            field=models.CharField(blank=True, default='no', max_length=20, null=True),
        ),
    ]
