# Generated by Django 3.2.6 on 2021-11-13 14:52

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('db_api', '0049_alter_yolo_image'),
        ('employee', '0006_auto_20211028_1450'),
        ('mylinebot', '0002_manager_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('timestamp', models.DateTimeField()),
                ('alert_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_api.yolo')),
                ('line_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'AlertNotification',
            },
        ),
    ]
