# Generated by Django 3.2.6 on 2021-11-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylinebot', '0003_alertnotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertnotification',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
