# Generated by Django 3.2.6 on 2021-11-18 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylinebot', '0004_alter_alertnotification_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotification',
            name='task_id',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
