# Generated by Django 3.2.6 on 2021-11-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylinebot', '0005_alertnotification_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertnotification',
            name='task_image_id',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
