# Generated by Django 3.2.6 on 2021-11-20 02:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20211028_1450'),
        ('db_api', '0049_alter_yolo_image'),
        ('mylinebot', '0006_alertnotification_task_image_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alertnotification',
            name='task_image_id',
        ),
        migrations.AddField(
            model_name='alertnotification',
            name='memo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AlertImageNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('task_id', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('alert_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='db_api.yolo_files')),
                ('line_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
            options={
                'db_table': 'AlertImageNotification',
            },
        ),
    ]
