# Generated by Django 3.2.6 on 2021-09-29 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20210918_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='lineid',
            field=models.CharField(blank=True, default='no', max_length=50),
        ),
    ]
