# Generated by Django 3.2.6 on 2021-09-30 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_lineid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='lineid',
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
