# Generated by Django 3.2.6 on 2021-09-30 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20210930_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='lineid',
            field=models.CharField(blank=True, default='no', max_length=50),
        ),
    ]
