# Generated by Django 3.2.6 on 2021-11-26 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_auto_20211028_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='line_username',
            field=models.CharField(blank=True, default='no', max_length=150),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lineid',
            field=models.CharField(blank=True, default='no', max_length=150),
        ),
    ]
